### PR TITLE
translation: improvements

### PR DESCRIPTION
**Pull request by oscfdezdz**
**Edit:** Hi, `translator-credits` is a convention used in the about dialog that should make it easier to manage translator credits. Although I am not sure how gettext works with crystal because in `POTFILES` there is no .cr files and there are some using gettext inside.

### CODE REVIEW

**Comment by GeopJr** [comment]
Woah, that's a lot, thanks!

On the `translator_credits` part, should `THANKS` (all translators) be used in default/English locale? (if you are not comfortable with Crystal, I'll commit it when I fully review the PR, I'm mostly asking for opinion on it)

I can also extract the names from `THANKS` instead of depending on translators to add their names, but `translator_credits` allows them to use their preferred (nick)name instead of their weblate user account's. Which one do you prefer?

**Comment by daPhipz** [comment]
I am a member of the German translation team over at  [Damned Lies](https://l10n.gnome.org/teams/de/). Usually, we "translate" `translator-credits` as

```
FIRSTNAME LASTNAME <email@addre.ss>, YEAR.
```

Since the translation of the original string `translator-credits` is different for each language (duh), only those who are responsible for this exact translation will show up in the credits (I will only show up in Gernan translations, a Greek translator only in Greek translations, for example).
If you want to display all translators regardless of the UI language, you would have to do this a different way.

**Comment by GeopJr** [comment]
Thanks for your input! At the moment, for translator credits, all translators get extracted from the po files (at compile time):

about dialog of collision with translator credits shown

(They are stored in a variable with the name `THANKS`, which is the one mentioned in my original reply)

Since default/English don't have a translator, it could be used instead of `translator-credits` (which will be empty). Also as mentioned in the original reply, I could just extract the translators of each language from `THANKS` instead of depending on them to add their name, however adding their names manually allows them to use a different (nick)name or even not include themselves at all if they don't want to be listed.

**Comment by oscfdezdz** [comment]
> On the `translator_credits` part, should `THANKS` (all translators) be used in default/English locale?
>
> I can also extract the names from `THANKS` instead of depending on translators to add their names, but `translator_credits` allows them to use their preferred (nick)name instead of their weblate user account's. Which one do you prefer?

I don't have a strong opinion on that, but if translators change or remove their names in the translation, would `THANKS` change it as well in English locale?

I would leave it up to translators to decide if they want to add themselves to the credits or not, a comment on how to do it would be enough.

**Comment by GeopJr** [comment]
Looks ready to be merged, thanks! (Final decision was to let translators choose how and if to be displayed in credits using `translator-credits`)

(P.S. I just saw the edit on the issue body 😅, xgettext doesn't support Crystal, so I omitted them from `POTFILES`, for now the only option is manually adding them to the pot file)

**Pull request merged**
